# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Math-Project3D
version:      1.02
version_from: lib/Math/Project3D.pm
installdirs:  site
requires:
    Math::MatrixReal:              1.9
    Test::More:                    0.44

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
